/*
 * ina219.c
 *
 *  Created on: Sep 4, 2026
 *      Author: swaro
 */
#include "ina219.h"


/*
 * I2C peripheral handle generated by CubeMX.
 *
 * It is defined in main.c.
 */
extern I2C_HandleTypeDef hi2c1;


/*
 * ============================================================
 * INA219 Register Map
 * ============================================================
 */

#define INA219_REG_CONFIG       0x00U

#define INA219_REG_SHUNT_VOLT   0x01U

#define INA219_REG_BUS_VOLT     0x02U

#define INA219_REG_POWER        0x03U

#define INA219_REG_CURRENT      0x04U

#define INA219_REG_CALIBRATION  0x05U


/*
 * INA219 configuration:
 *
 * Bus voltage range:
 *     32 V
 *
 * PGA:
 *     ±320 mV
 *
 * Bus ADC:
 *     12-bit
 *
 * Shunt ADC:
 *     12-bit
 *
 * Operating mode:
 *     Shunt + Bus, continuous
 */
#define INA219_CONFIG_VALUE     0x399FU


/*
 * Calibration value.
 *
 * This value depends on the shunt resistor and
 * desired current LSB.
 *
 * For the common INA219 module configuration,
 * we use a 0.1 ohm shunt and 1 mA current LSB.
 */
#define INA219_CALIBRATION_VALUE    4096U


/*
 * I2C address used by HAL functions.
 *
 * STM32 HAL expects the 7-bit address shifted left by 1.
 */
#define INA219_HAL_ADDRESS \
    (INA219_I2C_ADDRESS << 1U)


/*
 * I2C timeout.
 */
#define INA219_TIMEOUT_MS       100U


/*
 * Local helper functions.
 */
static HAL_StatusTypeDef INA219_WriteRegister(
    uint8_t reg,
    uint16_t value
);


static HAL_StatusTypeDef INA219_ReadRegister(
    uint8_t reg,
    uint16_t *value
);


/**
  * @brief Write a 16-bit value to an INA219 register.
  */
static HAL_StatusTypeDef INA219_WriteRegister(
    uint8_t reg,
    uint16_t value)
{
    uint8_t data[2];


    /*
     * INA219 registers are MSB first.
     */
    data[0] = (uint8_t)(value >> 8);

    data[1] = (uint8_t)(value & 0xFFU);


    return HAL_I2C_Mem_Write(
        &hi2c1,
        INA219_HAL_ADDRESS,
        reg,
        I2C_MEMADD_SIZE_8BIT,
        data,
        2U,
        INA219_TIMEOUT_MS
    );
}


/**
  * @brief Read a 16-bit INA219 register.
  */
static HAL_StatusTypeDef INA219_ReadRegister(
    uint8_t reg,
    uint16_t *value)
{
    uint8_t data[2];

    HAL_StatusTypeDef status;


    status = HAL_I2C_Mem_Read(
        &hi2c1,
        INA219_HAL_ADDRESS,
        reg,
        I2C_MEMADD_SIZE_8BIT,
        data,
        2U,
        INA219_TIMEOUT_MS
    );


    if (status != HAL_OK)
    {
        return status;
    }


    /*
     * INA219 sends MSB first.
     */
    *value =
        ((uint16_t)data[0] << 8U) |
        (uint16_t)data[1];


    return HAL_OK;
}


/**
  * @brief Initialize INA219.
  */
HAL_StatusTypeDef INA219_Init(void)
{
    HAL_StatusTypeDef status;


    /*
     * Configure INA219.
     */
    status =
        INA219_WriteRegister(
            INA219_REG_CONFIG,
            INA219_CONFIG_VALUE
        );


    if (status != HAL_OK)
    {
        return status;
    }


    /*
     * Configure current/power calibration.
     */
    status =
        INA219_WriteRegister(
            INA219_REG_CALIBRATION,
            INA219_CALIBRATION_VALUE
        );


    return status;
}


/**
  * @brief Read bus voltage.
  *
  * INA219 bus voltage LSB = 4 mV.
  */
HAL_StatusTypeDef INA219_ReadBusVoltage(
    uint16_t *voltage_mv)
{
    uint16_t raw_value;

    HAL_StatusTypeDef status;


    status =
        INA219_ReadRegister(
            INA219_REG_BUS_VOLT,
            &raw_value
        );


    if (status != HAL_OK)
    {
        return status;
    }


    /*
     * Bits 15:13 are status bits.
     *
     * Actual bus voltage starts at bit 3.
     *
     * Therefore:
     *
     *     voltage = raw >> 3
     *
     * Each LSB = 4 mV.
     */
    raw_value >>= 3U;


    *voltage_mv =
        (uint16_t)(raw_value * 4U);


    return HAL_OK;
}


/**
  * @brief Read shunt voltage.
  *
  * INA219 shunt voltage LSB = 10 uV.
  */
HAL_StatusTypeDef INA219_ReadShuntVoltage(
    int16_t *shunt_uv)
{
    uint16_t raw_value;

    HAL_StatusTypeDef status;


    status =
        INA219_ReadRegister(
            INA219_REG_SHUNT_VOLT,
            &raw_value
        );


    if (status != HAL_OK)
    {
        return status;
    }


    /*
     * Interpret register as signed 16-bit value.
     */
    *shunt_uv =
        (int16_t)raw_value;


    /*
     * Convert to microvolts.
     *
     * 1 LSB = 10 uV.
     */
    *shunt_uv =
        (int16_t)
        (
            (*shunt_uv) * 10
        );


    return HAL_OK;
}


/**
  * @brief Read current.
  *
  * With our calibration:
  *
  *     Current LSB = 1 mA
  *
  * Therefore raw current value corresponds
  * directly to milliamps.
  */
HAL_StatusTypeDef INA219_ReadCurrent(
    int16_t *current_ma)
{
    uint16_t raw_value;

    HAL_StatusTypeDef status;


    status =
        INA219_ReadRegister(
            INA219_REG_CURRENT,
            &raw_value
        );


    if (status != HAL_OK)
    {
        return status;
    }


    *current_ma =
        (int16_t)raw_value;


    return HAL_OK;
}


/**
  * @brief Read power.
  *
  * With our calibration:
  *
  *     Power LSB = 20 × Current LSB
  *
  * Current LSB = 1 mA
  *
  * Therefore:
  *
  *     Power LSB = 20 mW
  */
HAL_StatusTypeDef INA219_ReadPower(
    uint16_t *power_mw)
{
    uint16_t raw_value;

    HAL_StatusTypeDef status;


    status =
        INA219_ReadRegister(
            INA219_REG_POWER,
            &raw_value
        );


    if (status != HAL_OK)
    {
        return status;
    }


    *power_mw =
        (uint16_t)(raw_value * 20U);


    return HAL_OK;
}

